"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { MegaMenuDefault } from "./components/Navbar"
import { ThemeProvider } from "@material-tailwind/react";
import AddWorkout from "./components/AddWorkout"



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <MegaMenuDefault />
        <AddWorkout />
        {children}
      <Footer />
    </ ThemeProvider >

      </body>
    </html>
  );
}
